### ISSUE TITLE
commit b804de2303ca1bc6628f2ca30c4b232239183f56 in liri-wayland causes an odd cmake issue

### ISSUE THREAD

**Issue by n3rdopolis** [liri-archive/wayland-archived#4] opened 2017-01-04 03:47 UTC
Hi

Trying to configure liri-wayland since commit b804de2303ca1bc6628f2ca30c4b232239183f56 and after results in the below cmake error, the commit before is fine, I tried to grep -iR QWaylandXCompositeEglClientBufferIntegrationPlugin in my source directory, and it was only in qtwayland...

Thanks
```
CMake Error at /opt/lib/cmake/Qt5WaylandCompositor/Qt5WaylandCompositor_QWaylandXCompositeEglClientBufferIntegrationPlugin.cmake:2 (add_library):
  add_library cannot create imported target
  "Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /opt/lib/cmake/Qt5WaylandCompositor/Qt5WaylandCompositorConfig.cmake:141 (include)
  /opt/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:80 (find_package)


CMake Error at /opt/lib/cmake/Qt5WaylandCompositor/Qt5WaylandCompositor_QWaylandXCompositeGlxClientBufferIntegrationPlugin.cmake:2 (add_library):
  add_library cannot create imported target
  "Qt5::QWaylandXCompositeGlxClientBufferIntegrationPlugin" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /opt/lib/cmake/Qt5WaylandCompositor/Qt5WaylandCompositorConfig.cmake:141 (include)
  /opt/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:80 (find_package)
```

**Comment by plfiorini** [comment] 2017-01-04 06:44
Can't reproduce the issue with a rebuild.

Try `rm -fr /opt/lib/cmake/Qt5Wayland*` followed by `make && sudo make install` inside the qtwayland build directory.

**Comment by n3rdopolis** [comment] 2017-01-05 02:22
more testing, I can compile it when I check out the `5.8.0` branch, not the `5.8` branch, or the `v5.8.0-beta1` tag that I temporarily froze my qtwayland compile script to use

**Comment by plfiorini** [comment] 2017-01-28 08:38
Now that I have updated my qtwayland copy to today's 5.8 branch I can reproduce the issue.
The `Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin` target is defined by both Qt5Gui (`Qt5Gui_QWaylandXCompositeEglPlatformIntegrationPlugin.cmake`) and Qt5WaylandClient (`Qt5WaylandClient_QWaylandXCompositeEglClientBufferIntegrationPlugin.cmake`).

The `Qt5Gui_QWaylandXCompositeEglPlatformIntegrationPlugin.cmake` file must not be installed by Qt5Gui because it's already provided by Qt5WaylandClient, this seems an upstream bug to me.

Now I have removed /opt/qt5 and I'm rebuilding qt5 hoping that the problem was fixed upstream.

**Comment by plfiorini** [comment] 2017-01-28 11:34
Still happens this is a qtwayland bug.
The workaround is to `rm -f /opt/qt5/lib/cmake/Qt5WaylandClient/Qt5WaylandClient_QWaylandXCompositeGlxClientBufferIntegrationPlugin.cmake /opt/qt5/lib/cmake/Qt5WaylandClient/Qt5WaylandClient_QWaylandXCompositeEglClientBufferIntegrationPlugin.cmake`

Upstream bug reported here: https://bugreports.qt.io/browse/QTBUG-58491

**Comment by plfiorini** [comment] 2017-01-28 16:17
@n3rdopolis This seems to fix it, it's up for review now https://codereview.qt-project.org/#/c/183752/

**Comment by plfiorini** [comment] 2017-01-31 13:20
@n3rdopolis Fix merged upstream, the issue should be fixed now.

**Closed as completed by plfiorini** 2017-01-31 13:20 UTC
Labels: bug, upstream
