### ISSUE TITLE
liri-wayland doesn't compile due to EGL issues with qt 5.8

### ISSUE THREAD

**Issue by n3rdopolis** [liri-archive/wayland-archived#1] opened 2017-01-02 16:30 UTC
I have my qtbase 5.8 branch (not 5.8.0, not sure what the difference is) compiled with egl, using the following options

../configure -confirm-license  -opensource -qpa wayland -egl -prefix $INSTALLDIR -release -dbus -no-gtk -system-sqlite -no-warnings-are-errors -no-separate-debug-info -nomake tests -nomake examples -libinput

Upon building, I am getting these build errors, even after trying to add an include of EGL/egl.h to plugins/egldeviceintegration/wayland/eglfswaylandintegration.h
```
[ 96%] Built target lirixwaylandplugin
In file included from /opt/include/QtPlatformHeaders/QEGLNativeContext:1:0,
                 from /srcbuild/lirios-wayland/plugins/egldeviceintegration/wayland/eglfswaylandintegration.cpp:32:
/opt/include/QtPlatformHeaders/qeglnativecontext.h:56:34: error: expected ‘)’ before ‘ctx’
     QEGLNativeContext(EGLContext ctx, EGLDisplay dpy)
                                  ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h:61:5: error: ‘EGLContext’ does not name a type
     EGLContext context() const { return m_context; }
     ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h:62:5: error: ‘EGLDisplay’ does not name a type
     EGLDisplay display() const { return m_display; }
     ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h:65:5: error: ‘EGLContext’ does not name a type
     EGLContext m_context;
     ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h:66:5: error: ‘EGLDisplay’ does not name a type
     EGLDisplay m_display;
     ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h: In constructor ‘QEGLNativeContext::QEGLNativeContext()’:
/opt/include/QtPlatformHeaders/qeglnativecontext.h:52:11: error: class ‘QEGLNativeContext’ does not have any field named ‘m_context’
         : m_context(0),
           ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h:53:11: error: class ‘QEGLNativeContext’ does not have any field named ‘m_display’
           m_display(0)
           ^
/srcbuild/lirios-wayland/plugins/egldeviceintegration/wayland/eglfswaylandintegration.cpp: In member function ‘virtual QPlatformOpenGLContext* Liri::Platform::EglFSWaylandIntegration::createPlatformOpenGLContext(QOpenGLContext*)’:
/srcbuild/lirios-wayland/plugins/egldeviceintegration/wayland/eglfswaylandintegration.cpp:217:99: error: no matching function for call to ‘QEGLNativeContext::QEGLNativeContext(EGLContext, void*&)’
     nativeHandle = QVariant::fromValue<QEGLNativeContext>(QEGLNativeContext(ctx->eglContext(), dpy));
                                                                                                   ^
In file included from /opt/include/QtPlatformHeaders/QEGLNativeContext:1:0,
                 from /srcbuild/lirios-wayland/plugins/egldeviceintegration/wayland/eglfswaylandintegration.cpp:32:
/opt/include/QtPlatformHeaders/qeglnativecontext.h:51:5: note: candidate: QEGLNativeContext::QEGLNativeContext()
     QEGLNativeContext()
     ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h:51:5: note:   candidate expects 0 arguments, 2 provided
/opt/include/QtPlatformHeaders/qeglnativecontext.h:49:8: note: candidate: constexpr QEGLNativeContext::QEGLNativeContext(const QEGLNativeContext&)
 struct QEGLNativeContext
        ^
/opt/include/QtPlatformHeaders/qeglnativecontext.h:49:8: note:   candidate expects 1 argument, 2 provided
/opt/include/QtPlatformHeaders/qeglnativecontext.h:49:8: note: candidate: constexpr QEGLNativeContext::QEGLNativeContext(QEGLNativeContext&&)
/opt/include/QtPlatformHeaders/qeglnativecontext.h:49:8: note:   candidate expects 1 argument, 2 provided
plugins/egldeviceintegration/wayland/CMakeFiles/wayland.dir/build.make:134: recipe for target 'plugins/egldeviceintegration/wayland/CMakeFiles/wayland.dir/eglfswaylandintegration.cpp.o' failed
make[2]: *** [plugins/egldeviceintegration/wayland/CMakeFiles/wayland.dir/eglfswaylandintegration.cpp.o] Error 1
CMakeFiles/Makefile2:566: recipe for target 'plugins/egldeviceintegration/wayland/CMakeFiles/wayland.dir/all' failed
make[1]: *** [plugins/egldeviceintegration/wayland/CMakeFiles/wayland.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
```

**Comment by plfiorini** [comment] 2017-01-02 17:52
5.8 contains code that (at this point in time, past the RC) will be released along with Qt 5.8.1, while 5.8.0 contains hotfixes for bugs discovered while testing the RC and the code in this branch will be released along with Qt 5.8.0.

I build Qt from the 5.8 branch cloning the qt5 repository by instructions.
The qt5 repository has known good hashes for the submodules, qtbase is currently at 7957d0fbd71767055b1fa408d3a05d3892718c84.

I'm refreshing my build to see if this happens but so far I haven't seen this problem.

**Comment by plfiorini** [comment] 2017-01-02 21:46
This is my configure command line: ```./configure -opensource -confirm-license -prefix /opt/qt5 -egl```
This is the summary:

```
Configure summary:

Build type: linux-g++ (x86_64, CPU features: mmx sse sse2)
Configuration: use_gold_linker sse2 sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl compile_examples enable_new_dtags largefile precompile_header shared rpath accessibility release c++11 c++14 c++1z concurrent dbus mremap reduce_exports reduce_relocations stl
Build options:
  Mode ................................... release
  Building shared libraries .............. yes
  Using C++ standard ..................... C++1z
  Using gold linker ...................... yes
  Using new DTAGS ........................ yes
  Using precompiled headers .............. yes
  Using LTCG ............................. no
  Target compiler supports:
    SSE .................................. SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
    AVX .................................. AVX AVX2
    AVX512 ............................... F ER CD PF DQ BW VL IFMA VBMI
  Build parts ............................ libs tools
Qt modules and options:
  Qt Concurrent .......................... yes
  Qt D-Bus ............................... yes
  Qt D-Bus directly linked to libdbus .... yes
  Qt Gui ................................. yes
  Qt Widgets ............................. yes
Support enabled for:
  Accessibility .......................... yes
  Using pkg-config ....................... yes
  QML debugging .......................... yes
  udev ................................... yes
  Using system zlib ...................... yes
Qt Core:
  DoubleConversion ....................... yes
    Using system DoubleConversion ........ no
  GLib ................................... yes
  iconv .................................. no
  ICU .................................... yes
  Logging backends:
    journald ............................. no
    syslog ............................... no
    slog2 ................................ no
  Using system PCRE ...................... yes
Qt Network:
  getaddrinfo() .......................... yes
  getifaddrs() ........................... yes
  IPv6 ifname ............................ yes
  libproxy ............................... no
  OpenSSL ................................ yes
    Qt directly linked to OpenSSL ........ no
  SCTP ................................... no
  Use system proxies ..................... yes
Qt Sql:
  DB2 (IBM) .............................. no
  InterBase .............................. yes
  MySql .................................. no
  OCI (Oracle) ........................... no
  ODBC ................................... no
  PostgreSQL ............................. no
  SQLite2 ................................ no
  SQLite ................................. yes
    Using system provided SQLite ......... no
  TDS (Sybase) ........................... no
Qt Gui:
  FreeType ............................... yes
    Using system FreeType ................ yes
  HarfBuzz ............................... yes
    Using system HarfBuzz ................ yes
  Fontconfig ............................. yes
  Image formats:
    GIF .................................. yes
    ICO .................................. yes
    JPEG ................................. yes
      Using system libjpeg ............... yes
    PNG .................................. yes
      Using system libpng ................ yes
  OpenGL:
    EGL .................................. yes
    Desktop OpenGL ....................... yes
    OpenGL ES 2.0 ........................ no
    OpenGL ES 3.0 ........................ no
    OpenGL ES 3.1 ........................ no
  Session Management ..................... yes
Features used by QPA backends:
  evdev .................................. yes
  libinput ............................... yes
  mtdev .................................. yes
  tslib .................................. yes
  xkbcommon-evdev ........................ yes
QPA backends:
  DirectFB ............................... no
  EGLFS .................................. yes
  EGLFS details:
    EGLFS i.Mx6 .......................... no
    EGLFS i.Mx6 Wayland .................. no
    EGLFS EGLDevice ...................... yes
    EGLFS GBM ............................ yes
    EGLFS Mali ........................... no
    EGLFS Raspberry Pi ................... no
    EGL on X11 ........................... yes
  LinuxFB ................................ yes
  Mir client ............................. no
  X11:
    Using system provided XCB libraries .. yes
    EGL on X11 ........................... yes
    Xinput2 .............................. yes
    XCB XKB .............................. yes
    XLib ................................. yes
    Xrender .............................. yes
    XCB render ........................... yes
    XCB GLX .............................. yes
    XCB Xlib ............................. yes
    Using system-provided xkbcommon ...... yes
Qt Widgets:
  GTK+ ................................... yes
  Styles ................................. Fusion Windows
Qt PrintSupport:
  CUPS ................................... yes
QtXmlPatterns:
  XML schema support ..................... yes
Qt QML:
  QML interpreter ........................ yes
  QML network support .................... yes
Qt Quick:
  Direct3D 12 ............................ no
  AnimatedImage item ..................... yes
  Canvas item ............................ yes
  Support for Quick Designer ............. yes
  Flipable item .......................... yes
  GridView item .......................... yes
  ListView item .......................... yes
  Path support ........................... yes
  PathView item .......................... yes
  Positioner items ....................... yes
  ShaderEffect item ...................... yes
  Sprite item ............................ yes
Qt Wayland Drivers:
  EGL .................................... yes
  Rasberry Pi ............................ no
  XComposite EGL ......................... yes
  XComposite GLX ......................... yes
  DRM EGL ................................ yes
  libhybris EGL .......................... no
Qt Wayland Client ........................ yes
Qt Wayland Compositor .................... yes
Qt Bluetooth:
  BlueZ .................................. yes
  BlueZ Low Energy ....................... yes
  Linux Crypto API ....................... yes
Qt Multimedia:
  ALSA ................................... yes
  GStreamer 1.0 .......................... yes
  GStreamer 0.10 ......................... no
  Video for Linux ........................ yes
  OpenAL ................................. yes
  PulseAudio ............................. yes
  Resource Policy (libresourceqt5) ....... no
  DirectShow ............................. no
Qt Location:
  Gypsy GPS Daemon ....................... no
  WinRT Geolocation API .................. no
Qt Sensors:
  sensorfw ............................... no

Note: Dropped compiler flags '-pthread' when detecting library 'glib'.

Note: Dropped compiler flags '-pthread' when detecting library 'gtk3'.

Note: Dropped compiler flags '-pthread' when detecting library 'gstreamer'.

Note: Dropped compiler flags '-pthread' when detecting library 'gstreamer_app'.


Platform notes:

            - Also available for Linux: linux-clang linux-kcc linux-icc linux-cxx
```

**Comment by n3rdopolis** [comment] 2017-01-02 21:50
I tried with 7957d0fbd71767055b1fa408d3a05d3892718c84, and it still failed to compile, same errors

maybe it's my Mesa?
```
Configuration: use_gold_linker sse2 sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl compile_examples enable_new_dtags largefile precompile_header shared rpath accessibility debug c++11 c++14 c++1z concurrent dbus mremap reduce_exports reduce_relocations release_tools stl
Build options:
  Mode ................................... debug; optimized tools
  Building shared libraries .............. yes
  Using C++ standard ..................... C++1z
  Using gold linker ...................... yes
  Using new DTAGS ........................ yes
  Using precompiled headers .............. yes
  Using LTCG ............................. no
  Target compiler supports:
    SSE .................................. SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
    AVX .................................. AVX AVX2
    AVX512 ............................... F ER CD PF DQ BW VL IFMA VBMI
  Build parts ............................ libs tools
Qt modules and options:
  Qt Concurrent .......................... yes
  Qt D-Bus ............................... yes
  Qt D-Bus directly linked to libdbus .... yes
  Qt Gui ................................. yes
  Qt Widgets ............................. yes
Support enabled for:
  Accessibility .......................... yes
  Using pkg-config ....................... yes
  QML debugging .......................... yes
  udev ................................... yes
  Using system zlib ...................... yes
Qt Core:
  DoubleConversion ....................... yes
    Using system DoubleConversion ........ no
  GLib ................................... yes
  iconv .................................. no
  ICU .................................... yes
  Logging backends:
    journald ............................. no
    syslog ............................... no
    slog2 ................................ no
  Using system PCRE ...................... yes
Qt Network:
  getaddrinfo() .......................... yes
  getifaddrs() ........................... yes
  IPv6 ifname ............................ yes
  libproxy ............................... no
  OpenSSL ................................ yes
    Qt directly linked to OpenSSL ........ no
  SCTP ................................... no
  Use system proxies ..................... yes
Qt Sql:
  DB2 (IBM) .............................. no
  InterBase .............................. no
  MySql .................................. yes
  OCI (Oracle) ........................... no
  ODBC ................................... no
  PostgreSQL ............................. no
  SQLite2 ................................ no
  SQLite ................................. yes
    Using system provided SQLite ......... yes
  TDS (Sybase) ........................... no
Qt Gui:
  FreeType ............................... yes
    Using system FreeType ................ yes
  HarfBuzz ............................... yes
    Using system HarfBuzz ................ yes
  Fontconfig ............................. yes
  Image formats:
    GIF .................................. yes
    ICO .................................. yes
    JPEG ................................. yes
      Using system libjpeg ............... yes
    PNG .................................. yes
      Using system libpng ................ yes
  OpenGL:
    EGL .................................. yes
    Desktop OpenGL ....................... yes
    OpenGL ES 2.0 ........................ no
    OpenGL ES 3.0 ........................ no
    OpenGL ES 3.1 ........................ no
  Session Management ..................... yes
Features used by QPA backends:
  evdev .................................. yes
  libinput ............................... yes
  mtdev .................................. yes
  tslib .................................. no
  xkbcommon-evdev ........................ yes
QPA backends:
  DirectFB ............................... no
  EGLFS .................................. yes
  EGLFS details:
    EGLFS i.Mx6 .......................... no
    EGLFS i.Mx6 Wayland .................. no
    EGLFS EGLDevice ...................... yes
    EGLFS GBM ............................ yes
    EGLFS Mali ........................... no
    EGLFS Raspberry Pi ................... no
    EGL on X11 ........................... yes
  LinuxFB ................................ yes
  Mir client ............................. no
  X11:
    Using system provided XCB libraries .. yes
    EGL on X11 ........................... yes
    Xinput2 .............................. yes
    XCB XKB .............................. yes
    XLib ................................. yes
    Xrender .............................. yes
    XCB render ........................... yes
    XCB GLX .............................. yes
    XCB Xlib ............................. yes
    Using system-provided xkbcommon ...... yes
Qt Widgets:
  GTK+ ................................... no
  Styles ................................. Fusion Windows
Qt PrintSupport:
  CUPS ................................... yes

Note: Dropped compiler flags '-pthread' when detecting library 'glib'.


Platform notes:

            - Also available for Linux: linux-clang linux-kcc linux-icc linux-cxx
        

Qt is now configured for building. Just run 'make'.
Once everything is built, you must run 'make install'.
Qt will be installed into /opt

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.

PackagePrepareBuild finished in 22 seconds

```

EDIT: here is my config log for qtwayland
```
Checking for wayland... yes
Checking for xkbcommon... yes
Checking for wayland_cursor... yes
Checking for wayland_scanner... yes
Checking for wayland_egl... yes
Checking for brcm_egl... no
Checking for glx... yes
Checking for xcomposite... yes
Checking for drm_egl_server... yes
Checking for libhybris_egl_server... no
PackagePrepareBuild finished in 1 seconds
```

**Comment by plfiorini** [comment] 2017-01-03 06:13
Ok I managed to reproduce it, something must have been changed very recently.

**Comment by plfiorini** [comment] 2017-01-03 06:18
Commit 179045f36a16ce2f6cfaad1dbd9443b52b1bf8d3 might be the cause, it used to include <QtEglSupport/private/qt_egl_p.h> and now it dropped the include leaving the appropriate include to the client.

I cannot wait until all the changes required by Liri are part of the official eglfs so I can drop my fork, maintaining this stuff out of tree is a PITA :-/

**Closed as completed** 2017-01-03 06:22 UTC
